service: connectifi-hooks
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stackTags:
    classification: dev
    description: testing hooks

functions:
  index:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

  openfigi:
    handler: openfigi.handler
    events:
      - httpApi:
          path: /openfigi
          method: POST

  polygon:
    handler: polygon.handler
    events:
      - httpApi:
          path: /polygon
          method: POST

  slack:
    handler: slack.handler
    events:
      - httpApi:
          path: /slack
          method: POST

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin