service: connectifi-hooks
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 10
  stackTags:
    classification: dev
    description: testing hooks
    environment: "dev"

functions:
  index:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

  openfigi:
    handler: hooks/openfigi.handler
    events:
      - httpApi:
          path: /openfigi
          method: POST

  polygonHook:
    handler: hooks/polygon.handler
    events:
      - httpApi:
          path: /polygonHook
          method: POST

  slack:
    handler: hooks/slack.handler
    events:
      - httpApi:
          path: /slack
          method: POST

  mapLink:
    handler: actions/mapLink.handler
    events:
      - httpApi:
          path: /mapLink
          method: POST
  
  emailLink:
    handler: actions/emailLink.handler
    events:
      - httpApi:
          path: /emailLink
          method: POST

  teamsLink:
    handler: actions/teamsLink.handler
    events:
      - httpApi:
          path: /teamsLink
          method: POST

  openAI:
    handler: actions/openAI.handler
    events:
      - httpApi:
          path: /openAI
          method: POST

  polygonIO:
    handler: actions/polygonIO.handler
    events:
      - httpApi:
          path: /polygonIO
          method: POST
  
plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-plugin-resource-tagging