service: connectifi-hooks
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 10
  stackTags:
    classification: dev
    description: testing hooks
    environment: "dev"

functions:
  index:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

  openfigi:
    handler: hooks/openfigi.handler
    events:
      - httpApi:
          path: /openfigi
          method: POST

  polygon:
    handler: hooks/polygon.handler
    events:
      - httpApi:
          path: /polygon
          method: POST

  slack:
    handler: hooks/slack.handler
    events:
      - httpApi:
          path: /slack
          method: POST
    
  exate:
    handler: hooks/exate.handler
    events:
      - httpApi:
          path: /exate
          method: POST

  companyHQ:
    handler: actions/companyHQ.handler
    events:
      - httpApi:
          path: /companyHQ
          method: POST
  
  emailLink:
    handler: actions/emailLink.handler
    events:
      - httpApi:
          path: /emailLink
          method: POST

  teamsLink:
    handler: actions/teamsLink.handler
    events:
      - httpApi:
          path: /teamsLink
          method: POST

  openAI:
    handler: actions/openAI.handler
    events:
      - httpApi:
          path: /openAI
          method: POST
          
plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-plugin-resource-tagging