service: connectifi-hooks
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 10
  stackTags:
    classification: dev
    description: testing hooks and actions
    environment: "dev"

functions:
  index:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get

  deliveryhooks:
    handler: deliveryhooks.handler
    events:
      - httpApi:
          path: /deliveryhooks/{hook}
          method: POST

  # actions:
  #   handler: actions.handler
  #   events:
  #     - httpApi:
  #         path: /actions
  #         method: POST

  mapLink:
    handler: actions/mapLink.handler
    events:
      - httpApi:
          path: /mapLink
          method: POST
  
  emailLink:
    handler: actions/emailLink.handler
    events:
      - httpApi:
          path: /emailLink
          method: POST

  teamsLink:
    handler: actions/teamsLink.handler
    events:
      - httpApi:
          path: /teamsLink
          method: POST

  openAI:
    handler: actions/openAI.handler
    events:
      - httpApi:
          path: /openAI
          method: POST

  polygonIO:
    handler: actions/polygonIO.handler
    events:
      - httpApi:
          path: /polygonIO
          method: POST
  
plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-plugin-resource-tagging