service: connectifi-hooks
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 10
  memorySize: 2048
  stackTags:
    classification: dev
    description: testing hooks and actions
    environment: "dev"

functions:
  deliveryhooks:
    handler: src/index.deliveryHookHandler
    events:
      - httpApi:
          path: /deliveryhooks/{hook}
          method: POST

  actions:
    handler: src/index.actionHandler
    events:
      - httpApi:
          path: /actions/{action}
          method: POST

plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-plugin-resource-tagging
